COMPILER = clang++
FLAGS = --std=c++98 -Wall -Wextra -Werror 

map:
	@$(COMPILER) $(FLAGS)	Map_tests.cpp -o map.out 

stack:
	@$(COMPILER) $(FLAGS)	Stack_tests.cpp -o stack.out 

clean:
	rm -f vector.out map.out stack.out set.out
